version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0-focal
    steps:
      - checkout
      - run: find .
      - run: apt-get update
      - run: apt-get install jq -y
      - run: mkdir -p /usr/share/man/man1
      - run: apt-get install openjdk-11-jre-headless -y
      - run: echo 'export PATH=$HOME/.dotnet/tools:$PATH' >> $BASH_ENV
      - run: dotnet tool install --global dotnet-sonarscanner --version 5.0.4
      - run: bash ./bin/ci